const DsActionTypes = {
  //POST to ds
  POST_DS_SONGS_FETCHING: "POST_DS_SONGS_FETCHING",
  POST_DS_SONGS_SUCCESS: "POST_DS_SONGS_SUCCESS",
  POST_DS_SONGS_FAILURE: "POST_DS_SONGS_FAILURE",
  // Post to DS Token
  POST_DS_TOKEN_FETCHING: "POST_DS_TOKEN_FETCHING",
  POST_DS_TOKEN_SUCCESS: "POST_DS_TOKEN_SUCCESS",
  POST_DS_TOKEN_FAILURE: "POST_DS_TOKEN_FAILURE"
};

export default DsActionTypes;
