const SpotifyActionTypes = {
//GET users
    GET_USERS_FETCHING: 'GET_USERS_FETCHING',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
//GET logged in
    GET_LOGGED_IN_FETCHING: 'GET_LOGGED_IN_FETCHING',
    GET_LOGGED_IN_SUCCESS: 'GET_LOGGED_IN_SUCCESS',
    GET_LOGGED_IN_FAILURE: 'GET_LOGGED_IN_FAILURE',
//GET liked songs
    GET_LIKEDSONGS_FETCHING: 'GET_LIKEDSONGS_FETCHING',
    GET_LIKEDSONGS_SUCCESS: 'GET_LIKEDSONGS_SUCCESS',
    GET_LIKEDSONGS_FAILURE: 'GET_LIKEDSONGS_FAILURE',
//GET Track info
    GET_TRACK_INFO_FETCHING: 'GET_TRACK_INFO_FETCHING',
    GET_TRACK_INFO_SUCCESS: 'GET_TRACK_INFO_SUCCESS',
    GET_TRACK_INFO_FAILURE: 'GET_TRACK_INFO_FAILURE',
//GET Spotify Account details
    GET_SPOTIFY_PRIVATE_ACCOUNT_DETAILS_FETCHING: 'GET_SPOTIFY_PRIVATE_ACCOUNT_DETAILS_FETCHING',
    GET_SPOTIFY_PRIVATE_ACCOUNT_DETAILS_SUCCESS: 'GET_SPOTIFY_PRIVATE_ACCOUNT_DETAILS_SUCCESS',
    GET_SPOTIFY_PRIVATE_ACCOUNT_DETAILS_FAILURE: 'GET_SPOTIFY_PRIVATE_ACCOUNT_DETAILS_FAILURE',
//GET Current song
    GET_CURRENT_SONG_FETCHING: 'GET_CURRENT_SONG_FETCHING',
    GET_CURRENT_SONG_SUCCESS: 'GET_CURRENT_SONG_SUCCESS',
    GET_CURRENT_SONG_FAILURE: 'GET_CURRENT_SONG_FAILURE',

//-----------------------------------------KEEP THIS POTENTAL BUG IN MIND (type is same as above)-------------------------------------------------------
    PERSIST_USER_FETCHING: 'GET_CURRENT_SONG_FETCHING',
    PERSIST_USER_SUCCESS: 'GET_CURRENT_SONG_SUCCESS',
    PERSIST_USER_FAILURE: 'GET_CURRENT_SONG_FAILURE',
//------------------------------------------------------------------------------------------------------------------------------------------------------

//GET several tracks
    GET_SEVERAL_TRACKS_FETCHING: 'GET_SEVERAL_TRACKS_FETCHING',
    GET_SEVERAL_TRACKS_SUCCESS: 'GET_SEVERAL_TRACKS_SUCCESS',
    GET_SEVERAL_TRACKS_FAILURE: 'GET_SEVERAL_TRACKS_FAILURE',
//POST Creates a new playlist
    CREATE_PLAYLIST_FETCHING: 'CREATE_PLAYLIST_FETCHING',
    CREATE_PLAYLIST_SUCCESS: 'CREATE_PLAYLIST_SUCCESS',
    CREATE_PLAYLIST_FAILURE: 'CREATE_PLAYLIST_FAILURE',
//GET playlist
    GET_PLAYLIST_FETCHING: 'GET_PLAYLIST_FETCHING',
    GET_PLAYLIST_SUCCESS: 'GET_PLAYLIST_SUCCESS',
    GET_PLAYLIST_FAILURE: 'GET_PLAYLIST_FAILURE',
//POST to playlist
    ADD_TO_PLAYLIST_FETCHING: 'ADD_TO_PLAYLIST_FETCHING',
    ADD_TO_PLAYLIST_SUCCESS: 'ADD_TO_PLAYLIST_SUCCESS',
    ADD_TO_PLAYLIST_FAILURE: 'ADD_TO_PLAYLIST_FAILURE',
//DELETE Disliked song from playlist
    REMOVE_TRACK_FETCHING: 'REMOVE_TRACK_FETCHING',
    REMOVE_TRACK_SUCCESS: 'REMOVE_TRACK_SUCCESS',
    REMOVE_TRACK_FAILURE: 'REMOVE_TRACK_FAILURE',
//PUT does something??
    PUT_LIKEDSONG_START: 'PUT_LIKEDSONG_START',
    PUT_LIKEDSONG__SUCCESS: 'PUT_LIKEDSONG__SUCCESS',
    PUT_LIKEDSONG__FAILURE: 'PUT_LIKEDSONG__FAILURE',
}

export default SpotifyActionTypes;